server:
  port: 8080
spring:
  application:
    name: gateway80
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.155.145:8848
    gateway:
      discovery:      #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:      #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId/**，其中微服务应用名默认大写访问。
          enabled: true
      default-filter:
      routes:
      - id: user-server
        predicates:
        - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]
        uri: lb://ryan-story
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
logging:
  level:
    org.springframework.cloud.gateway: debug
